<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [

            // 1. آشنایی با اعداد صحیح (challange_id=1)
            ['title' => 'جمع دو عدد صحیح', 'content' => 'مجموع عددهای -3 و 7 چقدر است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['4', '10', '-4', '-10'], 'answer' => '4', 'score' => 1],
            ['title' => 'تفریق اعداد صحیح', 'content' => 'تفریق عدد 5 از -2 چه مقداری دارد؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['-7', '7', '3', '-3'], 'answer' => '-7', 'score' => 1],
            ['title' => 'ضرب اعداد صحیح', 'content' => 'حاصل ضرب -4 در 6 چند است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['-24', '24', '10', '-10'], 'answer' => '-24', 'score' => 1],
            ['title' => 'تقسیم اعداد صحیح', 'content' => 'تقسیم 12 بر -3 چقدر است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['-4', '4', '3', '-3'], 'answer' => '-4', 'score' => 1],
            ['title' => 'عدد مخالف', 'content' => 'عدد مخالف 8 چیست؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['-8', '8', '0', '1'], 'answer' => '-8', 'score' => 1],
            ['title' => 'مقایسه اعداد صحیح', 'content' => 'کدام عدد بزرگ‌تر است: -2 یا 3؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['-2', '3', 'برابرند', 'هیچ‌کدام'], 'answer' => '3', 'score' => 1],
            ['title' => 'قدر مطلق', 'content' => 'قدر مطلق عدد -7 چقدر است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['7', '-7', '0', '1'], 'answer' => '7', 'score' => 1],
            ['title' => 'عدد صفر', 'content' => 'مجموع صفر و هر عدد صحیح برابر با چه عددی است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['عدد اول', 'عدد دوم', '0', '1'], 'answer' => 'عدد دوم', 'score' => 1],
            ['title' => 'عدد زوج', 'content' => 'کدام عدد از گزینه‌ها زوج است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['3', '5', '8', '7'], 'answer' => '8', 'score' => 1],
            ['title' => 'عدد اول', 'content' => 'کدام عدد، عددی اول است؟', 'challange_id' => 1, 'difficulty' => 'easy', 'topic' => 'اعداد صحیح', 'options' => ['4', '6', '5', '9'], 'answer' => '5', 'score' => 1],

            // 2. حل معادلات ساده خطی (challange_id=2)
            ['title' => 'حل معادله 2x + 3 = 7 چیست؟', 'content' => 'مقدار x را بیابید که معادله 2x + 3 = 7 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['1', '2', '3', '4'], 'answer' => '2', 'score' => 2],
            ['title' => 'حل معادله 5x - 10 = 0 چیست؟', 'content' => 'مقدار x را بیابید که معادله 5x - 10 = 0 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['1', '2', '3', '4'], 'answer' => '2', 'score' => 2],
            ['title' => 'اگر 3x + 4 = 13، مقدار x چند است؟', 'content' => 'مقدار x را که معادله 3x + 4 = 13 را برقرار می‌کند، بیابید.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['3', '4', '5', '6'], 'answer' => '3', 'score' => 2],
            ['title' => 'حل معادله x - 5 = -2 چیست؟', 'content' => 'مقدار x را بیابید که معادله x - 5 = -2 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['2', '-3', '3', '-2'], 'answer' => '3', 'score' => 2],
            ['title' => 'اگر 4x + 7 = 23، مقدار x چند است؟', 'content' => 'مقدار x را که معادله 4x + 7 = 23 را برقرار می‌کند، بیابید.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['3', '4', '5', '6'], 'answer' => '4', 'score' => 2],
            ['title' => 'حل معادله 7x - 14 = 0 چیست؟', 'content' => 'مقدار x را بیابید که معادله 7x - 14 = 0 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['0', '1', '2', '3'], 'answer' => '2', 'score' => 2],
            ['title' => 'اگر -2x + 4 = 0، مقدار x چیست؟', 'content' => 'مقدار x را که معادله -2x + 4 = 0 را برقرار می‌کند، بیابید.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['-2', '2', '0', '1'], 'answer' => '2', 'score' => 2],
            ['title' => 'حل معادله x + 6 = 10 چیست؟', 'content' => 'مقدار x را بیابید که معادله x + 6 = 10 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['2', '3', '4', '5'], 'answer' => '4', 'score' => 2],
            ['title' => 'اگر 5x - 5 = 20، مقدار x چیست؟', 'content' => 'مقدار x را که معادله 5x - 5 = 20 را برقرار می‌کند، بیابید.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['3', '4', '5', '6'], 'answer' => '5', 'score' => 2],
            ['title' => 'حل معادله 3x + 9 = 0 چیست؟', 'content' => 'مقدار x را بیابید که معادله 3x + 9 = 0 را برقرار کند.', 'challange_id' => 2, 'difficulty' => 'easy', 'topic' => 'معادلات خطی', 'options' => ['-3', '3', '0', '-9'], 'answer' => '-3', 'score' => 2],

            // 3. آشنایی با اعداد گویا و اعشاری (challange_id=3)
            ['title' => 'کسر متناظر با عدد اعشاری 0.25 کدام است؟', 'content' => 'کسر متناظر با عدد اعشاری 0.25 را انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['1/2', '1/4', '3/4', '2/5'], 'answer' => '1/4', 'score' => 2],
            ['title' => 'مقدار عدد اعشاری 3/5 چند است؟', 'content' => 'عدد اعشاری متناظر با کسر 3/5 را انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.5', '0.6', '0.7', '0.8'], 'answer' => '0.6', 'score' => 2],
            ['title' => 'کدام عدد بزرگ‌تر است؟ 0.75 یا 0.7؟', 'content' => 'عدد بزرگ‌تر را بین 0.75 و 0.7 انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.75', '0.7', 'برابرند', 'هیچ‌کدام'], 'answer' => '0.75', 'score' => 2],
            ['title' => 'مجموع 0.3 و 0.2 چقدر است؟', 'content' => 'مجموع 0.3 و 0.2 را محاسبه کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.5', '0.6', '0.4', '0.7'], 'answer' => '0.5', 'score' => 2],
            ['title' => 'کسر متناظر با عدد مخلوط 1 1/2 چیست؟', 'content' => 'کسر متناظر با عدد مخلوط 1 و 1/2 را انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['3/2', '1/2', '5/2', '2/3'], 'answer' => '3/2', 'score' => 2],
            ['title' => 'حاصلضرب 0.5 در 0.4 چند است؟', 'content' => 'حاصلضرب 0.5 در 0.4 را محاسبه کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.2', '0.3', '0.4', '0.5'], 'answer' => '0.2', 'score' => 2],
            ['title' => 'تقسیم 0.6 بر 0.2 چند است؟', 'content' => 'تقسیم 0.6 بر 0.2 را محاسبه کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['3', '2', '4', '1'], 'answer' => '3', 'score' => 2],
            ['title' => 'کدام عدد اعشاری برابر با 1/3 است؟', 'content' => 'عدد اعشاری برابر با 1/3 را انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.33', '0.3', '0.34', '0.35'], 'answer' => '0.33', 'score' => 2],
            ['title' => '50% برابر است با عدد اعشاری؟', 'content' => 'عدد اعشاری متناظر با 50 درصد را انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.5', '0.05', '5', '50'], 'answer' => '0.5', 'score' => 2],
            ['title' => 'کدام عدد بزرگ‌تر است؟ 0.9 یا 0.99؟', 'content' => 'عدد بزرگ‌تر را بین 0.9 و 0.99 انتخاب کنید.', 'challange_id' => 3, 'difficulty' => 'easy', 'topic' => 'اعداد گویا و اعشاری', 'options' => ['0.9', '0.99', 'برابرند', '0.95'], 'answer' => '0.99', 'score' => 2],

            // 4. مفاهیم پایه هندسه (challange_id=4)
            ['title' => 'مجموع زاویه‌های داخلی یک مثلث چقدر است؟', 'content' => 'مجموع زاویه‌های داخلی هر مثلث چند درجه است؟', 'challange_id' => 4, 'difficulty' => 'easy', 'topic' => 'هندسه', 'options' => ['90 درجه', '180 درجه', '270 درجه', '360 درجه'], 'answer' => '180 درجه', 'score' => 2],
            ['title' => 'زاویه قائمه چند درجه است؟', 'content' => 'زاویه قائمه چند درجه است؟', 'challange_id' => 4, 'difficulty' => 'easy', 'topic' => 'هندسه', 'options' => ['45 درجه', '90 درجه', '60 درجه', '120 درجه'], 'answer' => '90 درجه', 'score' => 2],
            ['title' => 'یک مربع چند ضلع دارد؟', 'content' => 'یک مربع چند ضلع دارد؟', 'challange_id' => 4, 'difficulty' => 'easy', 'topic' => 'هندسه', 'options' => ['3', '4', '5', '6'], 'answer' => '4', 'score' => 2],
            ['title' => 'زاویه متقابل راس‌ها در یک مثلث متساوی‌الاضلاع چند درجه است؟', 'content' => 'زاویه هر راس در مثلث متساوی‌الاضلاع چند درجه است؟', 'challange_id' => 4, 'difficulty' => 'medium', 'topic' => 'هندسه', 'options' => ['60 درجه', '90 درجه', '45 درجه', '30 درجه'], 'answer' => '60 درجه', 'score' => 3],
            ['title' => 'طول محیط دایره‌ای با شعاع 7 چقدر است؟', 'content' => 'محیط دایره‌ای که شعاع آن 7 واحد است چقدر است؟', 'challange_id' => 4, 'difficulty' => 'medium', 'topic' => 'هندسه', 'options' => ['14π', '7π', '21π', '28π'], 'answer' => '14π', 'score' => 3],
            ['title' => 'زاویه داخلی یک پنج ضلعی منتظم چقدر است؟', 'content' => 'زاویه داخلی هر رأس در پنج ضلعی منتظم چند درجه است؟', 'challange_id' => 4, 'difficulty' => 'medium', 'topic' => 'هندسه', 'options' => ['108 درجه', '120 درجه', '90 درجه', '72 درجه'], 'answer' => '108 درجه', 'score' => 3],
            ['title' => 'مساحت مربع با ضلع 5 چقدر است؟', 'content' => 'مساحت مربع‌ای که طول ضلعش 5 واحد است چقدر است؟', 'challange_id' => 4, 'difficulty' => 'easy', 'topic' => 'هندسه', 'options' => ['10', '20', '25', '15'], 'answer' => '25', 'score' => 2],
            ['title' => 'در یک مثلث قائم‌الزاویه، مربع وتر برابر است با؟', 'content' => 'طبق قضیه فیثاغورس، مربع وتر یک مثلث قائم‌الزاویه برابر است با؟', 'challange_id' => 4, 'difficulty' => 'hard', 'topic' => 'هندسه', 'options' => ['جمع مربعات دو ضلع دیگر', 'حاصلضرب دو ضلع دیگر', 'تفریق دو ضلع دیگر', 'هیچ‌کدام'], 'answer' => 'جمع مربعات دو ضلع دیگر', 'score' => 4],
            ['title' => 'زاویه بین دو خط موازی چند درجه است؟', 'content' => 'زاویه بین دو خط موازی چقدر است؟', 'challange_id' => 4, 'difficulty' => 'easy', 'topic' => 'هندسه', 'options' => ['0 درجه', '90 درجه', '45 درجه', '60 درجه'], 'answer' => '0 درجه', 'score' => 2],
            ['title' => 'زاویه خارجی یک مثلث برابر است با؟', 'content' => 'زاویه خارجی یک رأس مثلث برابر است با؟', 'challange_id' => 4, 'difficulty' => 'medium', 'topic' => 'هندسه', 'options' => ['مجموع دو زاویه داخلی دیگر', 'یک زاویه داخلی', '90 درجه', '180 درجه'], 'answer' => 'مجموع دو زاویه داخلی دیگر', 'score' => 3],

            // 5. معادلات درجه دوم و کاربردها (challange_id=5)
            ['title' => 'ریشه‌های معادله x² - 5x + 6 = 0 چیست؟', 'content' => 'ریشه‌های معادله درجه دوم x² - 5x + 6 = 0 را بیابید.', 'challange_id' => 5, 'difficulty' => 'medium', 'topic' => 'معادلات درجه دوم', 'options' => ['2 و 3', '1 و 6', '3 و 4', '2 و 4'], 'answer' => '2 و 3', 'score' => 3],
            ['title' => 'مقدار دلتا در معادله x² + 4x + 3 = 0 چقدر است؟', 'content' => 'مقدار دلتا (Δ) در معادله x² + 4x + 3 = 0 چقدر است؟', 'challange_id' => 5, 'difficulty' => 'medium', 'topic' => 'معادلات درجه دوم', 'options' => ['4', '16', '1', '0'], 'answer' => '16', 'score' => 3],
            ['title' => 'معادله x² - 4 = 0 چه ریشه‌هایی دارد؟', 'content' => 'ریشه‌های معادله x² - 4 = 0 را بیابید.', 'challange_id' => 5, 'difficulty' => 'easy', 'topic' => 'معادلات درجه دوم', 'options' => ['2 و -2', '4 و -4', '1 و -1', '0 و 4'], 'answer' => '2 و -2', 'score' => 2],
            ['title' => 'رابطه ریشه‌ها و ضریب‌ها در x² + bx + c = 0 چیست؟', 'content' => 'رابطه بین ریشه‌ها و ضرایب معادله x² + bx + c = 0 چیست؟', 'challange_id' => 5, 'difficulty' => 'hard', 'topic' => 'معادلات درجه دوم', 'options' => ['جمع ریشه‌ها = -b', 'ضرب ریشه‌ها = c', 'جمع ریشه‌ها = c', 'ضرب ریشه‌ها = -b'], 'answer' => 'جمع ریشه‌ها = -b', 'score' => 4],
            ['title' => 'اگر معادله درجه دوم x² + px + q = 0 دو ریشه مساوی داشته باشد، مقدار دلتا چیست؟', 'content' => 'دلتا (Δ) در معادله‌ای که دو ریشه مساوی دارد چقدر است؟', 'challange_id' => 5, 'difficulty' => 'hard', 'topic' => 'معادلات درجه دوم', 'options' => ['صفر', 'یک', 'دو', 'منفی'], 'answer' => 'صفر', 'score' => 4],
            ['title' => 'مقدار x وقتی معادله 3x² - 12x + 9 = 0 برقرار است چیست؟', 'content' => 'ریشه‌های معادله 3x² - 12x + 9 = 0 را بیابید.', 'challange_id' => 5, 'difficulty' => 'medium', 'topic' => 'معادلات درجه دوم', 'options' => ['1 و 3', '2 و 3', '1 و 4', '3 و 4'], 'answer' => '1 و 3', 'score' => 3],
            ['title' => 'مجموع ریشه‌های معادله 2x² - 7x + 3 = 0 چیست؟', 'content' => 'مجموع ریشه‌های معادله 2x² - 7x + 3 = 0 را بیابید.', 'challange_id' => 5, 'difficulty' => 'medium', 'topic' => 'معادلات درجه دوم', 'options' => ['7/2', '-7/2', '3/2', '-3/2'], 'answer' => '7/2', 'score' => 3],
            ['title' => 'ضرب ریشه‌های معادله x² - 6x + 8 = 0 چیست؟', 'content' => 'ضرب ریشه‌های معادله x² - 6x + 8 = 0 را بیابید.', 'challange_id' => 5, 'difficulty' => 'medium', 'topic' => 'معادلات درجه دوم', 'options' => ['8', '-8', '6', '-6'], 'answer' => '8', 'score' => 3],
            ['title' => 'اگر یکی از ریشه‌های معادله  x² - 5x + k = 0 عدد 2 باشد، مقدار k چیست؟', 'content' => 'مقدار k را در معادله x² - 5x + k = 0 پیدا کنید، اگر یکی از ریشه‌ها 2 باشد.', 'challange_id' => 5, 'difficulty' => 'hard', 'topic' => 'معادلات درجه دوم', 'options' => ['2', '4', '6', '8'], 'answer' => '4', 'score' => 4],
            ['title' => 'محل تقاطع نمودار معادله درجه دوم با محور x چیست؟', 'content' => 'نمودار معادله درجه دوم با محور x در چه نقاطی تقاطع دارد؟', 'challange_id' => 5, 'difficulty' => 'easy', 'topic' => 'معادلات درجه دوم', 'options' => ['ریشه‌ها', 'رأس', 'محور y', 'هیچ‌کدام'], 'answer' => 'ریشه‌ها', 'score' => 2],

            // 6. مثلثات مقدماتی (challange_id=6)
            ['title' => 'مقدار sin(30°) چقدر است؟', 'content' => 'مقدار سینوس زاویه 30 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['1', '1/2', '√3/2', '0'], 'answer' => '1/2', 'score' => 3],
            ['title' => 'مقدار cos(60°) چقدر است؟', 'content' => 'مقدار کسینوس زاویه 60 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['1/2', '1', '0', '√3/2'], 'answer' => '1/2', 'score' => 3],
            ['title' => 'tan(45°) برابر است با؟', 'content' => 'مقدار تانژانت زاویه 45 درجه چیست؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['1', '0', '√3', '-1'], 'answer' => '1', 'score' => 3],
            ['title' => 'مقدار sin(90°) چقدر است؟', 'content' => 'مقدار سینوس زاویه 90 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['0', '1', '1/2', '√3/2'], 'answer' => '1', 'score' => 3],
            ['title' => 'sin(0°) برابر است با؟', 'content' => 'مقدار سینوس زاویه صفر درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['0', '1', '-1', '√2/2'], 'answer' => '0', 'score' => 3],
            ['title' => 'tan(0°) برابر است با؟', 'content' => 'مقدار تانژانت زاویه صفر درجه چیست؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['0', '1', '∞', '-1'], 'answer' => '0', 'score' => 3],
            ['title' => 'sin(45°) برابر است با؟', 'content' => 'مقدار سینوس زاویه 45 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'medium', 'topic' => 'مثلثات', 'options' => ['√2/2', '1/2', '1', '0'], 'answer' => '√2/2', 'score' => 4],
            ['title' => 'cos(45°) برابر است با؟', 'content' => 'مقدار کسینوس زاویه 45 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'medium', 'topic' => 'مثلثات', 'options' => ['√2/2', '1/2', '1', '0'], 'answer' => '√2/2', 'score' => 4],
            ['title' => 'tan(60°) برابر است با؟', 'content' => 'مقدار تانژانت زاویه 60 درجه چیست؟', 'challange_id' => 6, 'difficulty' => 'medium', 'topic' => 'مثلثات', 'options' => ['√3', '1', '√2', '0'], 'answer' => '√3', 'score' => 4],
            ['title' => 'sin(180°) برابر است با؟', 'content' => 'مقدار سینوس زاویه 180 درجه چقدر است؟', 'challange_id' => 6, 'difficulty' => 'easy', 'topic' => 'مثلثات', 'options' => ['0', '1', '-1', '√3/2'], 'answer' => '0', 'score' => 3],

            // 7. مفاهیم اولیه آمار و احتمال (challange_id=7)
            ['title' => 'احتمال انداختن شیر در سکه چقدر است؟', 'content' => 'احتمال آمدن شیر در پرتاب یک سکه عادلانه چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1', '1/2', '1/4', '0'], 'answer' => '1/2', 'score' => 3],
            ['title' => 'احتمال آمدن عدد زوج در تاس چند است؟', 'content' => 'احتمال آمدن عدد زوج در پرتاب یک تاس استاندارد چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1/2', '1/3', '1/6', '2/3'], 'answer' => '1/2', 'score' => 3],
            ['title' => 'احتمال بیرون آمدن عدد 5 در تاس چند است؟', 'content' => 'احتمال بیرون آمدن عدد 5 در پرتاب یک تاس چند است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1/6', '1/3', '1/2', '1'], 'answer' => '1/6', 'score' => 3],
            ['title' => 'احتمال آمدن شیر یا خط در سکه چند است؟', 'content' => 'احتمال آمدن شیر یا خط در پرتاب سکه چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1', '1/2', '1/4', '0'], 'answer' => '1', 'score' => 3],
            ['title' => 'اگر احتمال بارش باران 0.3 باشد، احتمال نباریدن چقدر است؟', 'content' => 'اگر احتمال بارش باران 0.3 باشد، احتمال نباریدن باران چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['0.7', '0.3', '0.5', '1'], 'answer' => '0.7', 'score' => 3],
            ['title' => 'احتمال بیرون آمدن عدد فرد در تاس چند است؟', 'content' => 'احتمال آمدن عدد فرد در پرتاب یک تاس چند است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1/2', '1/3', '1/6', '2/3'], 'answer' => '1/2', 'score' => 3],
            ['title' => 'اگر احتمال موفقیت 0.8 باشد، احتمال شکست چقدر است؟', 'content' => 'اگر احتمال موفقیت 0.8 باشد، احتمال شکست چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['0.2', '0.8', '0.5', '1'], 'answer' => '0.2', 'score' => 3],
            ['title' => 'احتمال آمدن عدد بزرگ‌تر از 4 در تاس چند است؟', 'content' => 'احتمال آمدن عدد بزرگ‌تر از 4 در پرتاب یک تاس چند است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1/3', '1/2', '1/6', '2/3'], 'answer' => '1/3', 'score' => 3],
            ['title' => 'احتمال بیرون آمدن عدد کمتر از 3 در تاس چند است؟', 'content' => 'احتمال آمدن عدد کمتر از 3 در پرتاب یک تاس چند است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['1/3', '1/2', '1/6', '2/3'], 'answer' => '1/3', 'score' => 3],
            ['title' => 'اگر احتمال یک رویداد 0.5 باشد، احتمال عدم وقوع آن چقدر است؟', 'content' => 'اگر احتمال وقوع یک رویداد 0.5 باشد، احتمال عدم وقوع آن چقدر است؟', 'challange_id' => 7, 'difficulty' => 'easy', 'topic' => 'آمار و احتمال', 'options' => ['0.5', '0.7', '0.3', '1'], 'answer' => '0.5', 'score' => 3],

            // 8. حل معادلات دیفرانسیل ساده (challange_id=8)
            ['title' => 'حل معادله dy/dx = 3x² چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 3x² چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['x³ + C', '3x² + C', '2x + C', 'x² + C'], 'answer' => 'x³ + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = 0 چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 0 چیست؟', 'challange_id' => 8, 'difficulty' => 'medium', 'topic' => 'معادلات دیفرانسیل', 'options' => ['C', '0', 'x', '1'], 'answer' => 'C', 'score' => 4],
            ['title' => 'حل معادله dy/dx = 6x چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 6x چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['3x² + C', '6x + C', 'x² + C', '2x + C'], 'answer' => '3x² + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = e^x چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = e^x چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['e^x + C', 'xe^x + C', 'x + C', 'e + C'], 'answer' => 'e^x + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = sin(x) چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = sin(x) چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['-cos(x) + C', 'cos(x) + C', 'sin(x) + C', '-sin(x) + C'], 'answer' => '-cos(x) + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = 1/x چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 1/x چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['ln|x| + C', 'x + C', '1/x + C', 'x² + C'], 'answer' => 'ln|x| + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = 0.5x چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 0.5x چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['0.25x² + C', '0.5x + C', 'x + C', '0.5x² + C'], 'answer' => '0.25x² + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = cos(x) چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = cos(x) چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['sin(x) + C', '-sin(x) + C', 'cos(x) + C', '-cos(x) + C'], 'answer' => 'sin(x) + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = 2x^3 چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 2x^3 چیست؟', 'challange_id' => 8, 'difficulty' => 'hard', 'topic' => 'معادلات دیفرانسیل', 'options' => ['0.5x^4 + C', '2x^3 + C', 'x^4 + C', '4x^3 + C'], 'answer' => '0.5x^4 + C', 'score' => 5],
            ['title' => 'حل معادله dy/dx = 1 چیست؟', 'content' => 'حل معادله دیفرانسیل dy/dx = 1 چیست؟', 'challange_id' => 8, 'difficulty' => 'medium', 'topic' => 'معادلات دیفرانسیل', 'options' => ['x + C', '1 + C', '0 + C', 'C'], 'answer' => 'x + C', 'score' => 4],

            // 9. تحلیل بردارها و ماتریس‌ها (challange_id=9)
            ['title' => 'جمع بردارهای (1,2) و (3,4) چیست؟', 'content' => 'جمع بردارهای (1,2) و (3,4) را محاسبه کنید.', 'challange_id' => 9, 'difficulty' => 'medium', 'topic' => 'بردارها', 'options' => ['(4,6)', '(3,6)', '(2,3)', '(1,2)'], 'answer' => '(4,6)', 'score' => 4],
            ['title' => 'ضرب داخلی بردارهای (1,3) و (4,2) چیست؟', 'content' => 'ضرب داخلی بردارهای (1,3) و (4,2) را محاسبه کنید.', 'challange_id' => 9, 'difficulty' => 'hard', 'topic' => 'بردارها', 'options' => ['10', '8', '7', '5'], 'answer' => '10', 'score' => 5],
            ['title' => 'بردار صفر چیست؟', 'content' => 'بردار صفر را مشخص کنید.', 'challange_id' => 9, 'difficulty' => 'easy', 'topic' => 'بردارها', 'options' => ['(0,0)', '(1,1)', '(1,0)', '(0,1)'], 'answer' => '(0,0)', 'score' => 3],
            ['title' => 'ماتریس واحد 2×2 چیست؟', 'content' => 'ماتریس واحد 2×2 را مشخص کنید.', 'challange_id' => 9, 'difficulty' => 'medium', 'topic' => 'ماتریس‌ها', 'options' => ['[[1,0],[0,1]]', '[[0,1],[1,0]]', '[[1,1],[1,1]]', '[[0,0],[0,0]]'], 'answer' => '[[1,0],[0,1]]', 'score' => 4],
            ['title' => 'تبدیل ماتریس A به ماتریس B معکوس نامیده می‌شود اگر؟', 'content' => 'تبدیل ماتریس A به ماتریس B را معکوس می‌نامند اگر چه شرطی برقرار باشد؟', 'challange_id' => 9, 'difficulty' => 'hard', 'topic' => 'ماتریس‌ها', 'options' => ['A×B=I', 'A+B=I', 'A-B=I', 'A×B=0'], 'answer' => 'A×B=I', 'score' => 5],
            ['title' => 'مقدار دترمینان ماتریس [[1,2],[3,4]] چیست؟', 'content' => 'مقدار دترمینان ماتریس [[1,2],[3,4]] را حساب کنید.', 'challange_id' => 9, 'difficulty' => 'hard', 'topic' => 'ماتریس‌ها', 'options' => ['-2', '2', '10', '-10'], 'answer' => '-2', 'score' => 5],
            ['title' => 'اگر بردارهای (2,3) و (4,6) چه نسبتی دارند؟', 'content' => 'بردارهای (2,3) و (4,6) چه نسبتی دارند؟', 'challange_id' => 9, 'difficulty' => 'medium', 'topic' => 'بردارها', 'options' => ['موازی', 'عمود', 'مساوی', 'ناهمگون'], 'answer' => 'موازی', 'score' => 4],
            ['title' => 'بردار عمود بر بردار (1,0) کدام است؟', 'content' => 'بردار عمود بر بردار (1,0) کدام گزینه است؟', 'challange_id' => 9, 'difficulty' => 'medium', 'topic' => 'بردارها', 'options' => ['(0,1)', '(1,0)', '(1,1)', '(0,0)'], 'answer' => '(0,1)', 'score' => 4],
            ['title' => 'ماتریس قطری چیست؟', 'content' => 'ماتریس قطری چگونه ماتریسی است؟', 'challange_id' => 9, 'difficulty' => 'easy', 'topic' => 'ماتریس‌ها', 'options' => ['فقط عناصر روی قطر غیر صفرند', 'همه عناصر غیر صفرند', 'همه عناصر صفرند', 'تمام عناصر غیر قطر صفرند'], 'answer' => 'فقط عناصر روی قطر غیر صفرند', 'score' => 3],
            ['title' => 'جمع دو ماتریس 2×2 چگونه محاسبه می‌شود؟', 'content' => 'جمع دو ماتریس 2×2 چگونه انجام می‌شود؟', 'challange_id' => 9, 'difficulty' => 'easy', 'topic' => 'ماتریس‌ها', 'options' => ['جمع عنصر به عنصر', 'ضرب عنصر به عنصر', 'ماتریس جدید تصادفی', 'هیچ‌کدام'], 'answer' => 'جمع عنصر به عنصر', 'score' => 3],

            // 10. معماهای ریاضی ترکیبی (challange_id=10)
            ['title' => 'اگر دو عدد متوالی جمعشان 15 است، اعداد کدام‌اند؟', 'content' => 'دو عدد متوالی که جمعشان 15 است، کدام‌اند؟', 'challange_id' => 10, 'difficulty' => 'medium', 'topic' => 'معماهای ریاضی', 'options' => ['7 و 8', '6 و 7', '8 و 9', '5 و 10'], 'answer' => '7 و 8', 'score' => 4],
            ['title' => 'اگر سه عدد متوالی جمعشان 30 باشد، اعداد چیستند؟', 'content' => 'سه عدد متوالی که جمعشان 30 است، کدام‌اند؟', 'challange_id' => 10, 'difficulty' => 'hard', 'topic' => 'معماهای ریاضی', 'options' => ['9،10،11', '8،9،10', '7،8،9', '10،11،12'], 'answer' => '9،10،11', 'score' => 5],
            ['title' => 'اگر نصف عددی 7 باشد، آن عدد چیست؟', 'content' => 'اگر نصف عددی 7 باشد، عدد اصلی چیست؟', 'challange_id' => 10, 'difficulty' => 'easy', 'topic' => 'معماهای ریاضی', 'options' => ['14', '7', '10', '21'], 'answer' => '14', 'score' => 3],
            ['title' => 'اگر x+y=10 و x-y=2 باشد، x چند است؟', 'content' => 'اگر x+y=10 و x-y=2 باشد، مقدار x چقدر است؟', 'challange_id' => 10, 'difficulty' => 'hard', 'topic' => 'معماهای ریاضی', 'options' => ['6', '4', '5', '7'], 'answer' => '6', 'score' => 5],
            ['title' => 'عدد بزرگ‌تر از 20 و کوچک‌تر از 25 کدام است؟', 'content' => 'عددی که بزرگ‌تر از 20 و کوچک‌تر از 25 است کدام است؟', 'challange_id' => 10, 'difficulty' => 'easy', 'topic' => 'معماهای ریاضی', 'options' => ['21', '25', '19', '30'], 'answer' => '21', 'score' => 3],
            ['title' => 'مجموع اعداد 1 تا 5 چند است؟', 'content' => 'مجموع اعداد 1 تا 5 چند است؟', 'challange_id' => 10, 'difficulty' => 'easy', 'topic' => 'معماهای ریاضی', 'options' => ['15', '10', '20', '25'], 'answer' => '15', 'score' => 3],
            ['title' => 'اگر نصف x برابر 10 باشد، x چیست؟', 'content' => 'اگر نصف x برابر 10 باشد، مقدار x چیست؟', 'challange_id' => 10, 'difficulty' => 'medium', 'topic' => 'معماهای ریاضی', 'options' => ['20', '10', '5', '15'], 'answer' => '20', 'score' => 4],
            ['title' => 'تعداد اعداد فرد بین 1 تا 10 چند است؟', 'content' => 'تعداد اعداد فرد بین 1 تا 10 چند عدد است؟', 'challange_id' => 10, 'difficulty' => 'easy', 'topic' => 'معماهای ریاضی', 'options' => ['5', '4', '6', '7'], 'answer' => '5', 'score' => 3],
            ['title' => 'اگر x² = 49، مقدار x چیست؟', 'content' => 'اگر x² = 49، مقدار x چند است؟', 'challange_id' => 10, 'difficulty' => 'medium', 'topic' => 'معماهای ریاضی', 'options' => ['7', '-7', '7 یا -7', 'هیچ‌کدام'], 'answer' => '7 یا -7', 'score' => 4],
            ['title' => 'اگر x + 3 = 7، مقدار x چیست؟', 'content' => 'اگر x + 3 = 7 باشد، مقدار x چقدر است؟', 'challange_id' => 10, 'difficulty' => 'easy', 'topic' => 'معماهای ریاضی', 'options' => ['4', '3', '7', '10'], 'answer' => '4', 'score' => 3],

            // 11. حل مسائل چندمرحله‌ای با استدلال‌های پیچیده (challange_id=11)
            ['title' => 'اگر 3x + 5 = 20، مقدار x چقدر است؟', 'content' => 'مقدار x را بیابید که 3x + 5 = 20 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['3', '4', '5', '6'], 'answer' => '5', 'score' => 6],
            ['title' => 'اگر 2(x - 3) = 10، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 2(x - 3) = 10 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['8', '7', '6', '9'], 'answer' => '8', 'score' => 6],
            ['title' => 'اگر 5x - 4 = 16، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 5x - 4 = 16 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['4', '5', '6', '3'], 'answer' => '4', 'score' => 6],
            ['title' => 'اگر 4(x + 2) = 20، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 4(x + 2) = 20 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['3', '4', '5', '6'], 'answer' => '3', 'score' => 6],
            ['title' => 'اگر (x - 1)/2 = 3، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که (x - 1)/2 = 3 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['7', '8', '9', '6'], 'answer' => '7', 'score' => 6],
            ['title' => 'اگر 3(x - 2) + 4 = 16، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 3(x - 2) + 4 = 16 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['6', '7', '5', '8'], 'answer' => '6', 'score' => 6],
            ['title' => 'اگر 2x + 3(x - 1) = 12، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 2x + 3(x - 1) = 12 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['3', '4', '5', '2'], 'answer' => '3', 'score' => 6],
            ['title' => 'اگر 5(x + 1) - 2x = 18، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 5(x + 1) - 2x = 18 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['3', '4', '2', '5'], 'answer' => '3', 'score' => 6],
            ['title' => 'اگر 4(x - 3) + 5 = 17، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 4(x - 3) + 5 = 17 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['6', '5', '4', '7'], 'answer' => '6', 'score' => 6],
            ['title' => 'اگر 3(x + 2) - 4 = 11، مقدار x چیست؟', 'content' => 'مقدار x را بیابید که 3(x + 2) - 4 = 11 را برقرار می‌کند.', 'challange_id' => 11, 'difficulty' => 'hard', 'topic' => 'حل مسائل', 'options' => ['3', '4', '5', '6'], 'answer' => '3', 'score' => 6],

            // 12. مسائل مسابقات ریاضی و المپیادها (challange_id=12)
            ['title' => 'اگر 5 نفر به یک دورهمی بیایند، چند دست دو نفره می‌توان تشکیل داد؟', 'content' => 'اگر 5 نفر در دورهمی باشند، چند جفت دو نفره می‌توان تشکیل داد؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['10', '20', '15', '25'], 'answer' => '10', 'score' => 8],
            ['title' => 'عدد اول بزرگ‌تر از 20 کدام است؟', 'content' => 'عدد اول بزرگ‌تر از 20 کدام عدد است؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['23', '21', '25', '27'], 'answer' => '23', 'score' => 8],
            ['title' => 'اگر مجموع دو عدد 30 و اختلاف آنها 4 باشد، عدد بزرگ‌تر چیست؟', 'content' => 'اگر مجموع دو عدد 30 و اختلافشان 4 باشد، عدد بزرگ‌تر کدام است؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['17', '16', '15', '14'], 'answer' => '17', 'score' => 8],
            ['title' => 'اگر عددی را 5 برابر کنیم و 10 کم کنیم، حاصل 20 است. عدد چیست؟', 'content' => 'اگر عددی را 5 برابر کرده و 10 کم کنیم حاصل 20 شود، آن عدد چیست؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['6', '5', '4', '3'], 'answer' => '6', 'score' => 8],
            ['title' => 'اگر x و y اعداد صحیح و x + y = 12 و x - y = 4، مقدار x چیست؟', 'content' => 'اگر x و y اعداد صحیح باشند و x + y = 12 و x - y = 4، مقدار x چقدر است؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['8', '6', '7', '9'], 'answer' => '8', 'score' => 8],
            ['title' => 'مجموع زوایای داخلی یک هشت ضلعی چند درجه است؟', 'content' => 'مجموع زوایای داخلی یک هشت ضلعی چند درجه است؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['1080', '900', '720', '1260'], 'answer' => '1080', 'score' => 8],
            ['title' => 'مقدار n اگر n! = 120 باشد، چیست؟', 'content' => 'اگر n! = 120 باشد، مقدار n چیست؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['5', '6', '4', '7'], 'answer' => '5', 'score' => 8],
            ['title' => 'اگر مجموع دو عدد 50 باشد و یکی از اعداد 30 است، عدد دیگر چیست؟', 'content' => 'اگر مجموع دو عدد 50 و یکی از آنها 30 باشد، عدد دیگر چیست؟', 'challange_id' => 12, 'difficulty' => 'medium', 'topic' => 'مسابقات ریاضی', 'options' => ['20', '25', '15', '10'], 'answer' => '20', 'score' => 7],
            ['title' => 'اگر مجموع دو عدد 100 باشد و تفاضل آنها 40، عدد بزرگ‌تر چیست؟', 'content' => 'اگر مجموع دو عدد 100 و تفاضلشان 40 باشد، عدد بزرگ‌تر چیست؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['70', '60', '50', '55'], 'answer' => '70', 'score' => 8],
            ['title' => 'عدد 7 چند بار در حاصل ضرب اعداد 1 تا 14 وجود دارد؟', 'content' => 'عدد 7 چند بار در حاصل ضرب اعداد 1 تا 14 وجود دارد؟', 'challange_id' => 12, 'difficulty' => 'hard', 'topic' => 'مسابقات ریاضی', 'options' => ['2', '3', '1', '4'], 'answer' => '2', 'score' => 8],

        ];
        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
